version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   VITE_API_URL: ${VITE_API_URL}
    ports:
      - "5173:80"
    volumes:
      - .:/app
      - /app/node_modules
    # environment:
    #   NODE_ENV: production
    #   VITE_API_URL: ${VITE_API_URL}